const BIO_HEADER = `[**Bio**](https://portofliokarak.vercel.app/blog/minfo)

→
September 27, 2020 \\| Reading time: 8 minutes
`;

const BIO_VARIANT_BODIES = [
  `Karak was born in Howrah, grew up in Faridabad, and eventually found his way to Jhalda, where elephants occasionally show up to steal jackfruits and leave without explanation. This early exposure to unpredictable systems prepared him well for a career in product design.He studied architecture in Murthal before moving to Jodhpur for design, trading concrete for constraints and buildings for user flows. He now designs systems for shopkeepers using 4G internet that behaves like 3G, on phones that are already out of memory and patience.He currently lives in Bengaluru, where he cooks quickly, avoids cleaning utensils, and distrusts restaurants that look recently renovated. He suspects that if something works too smoothly, it probably hasn’t been tested properly.`,
  `Karak believes that good food is inversely proportional to how clean a place looks. This theory has led him to eat at establishments that appear structurally uncertain but socially validated.Raised between dust, red soil, and mustard oil, he developed a habit of trusting environments that reveal themselves slowly. This instinct now informs his work designing for small businesses, where decisions are made under pressure and rarely revisited.He lives in Bengaluru, drives with the windows open to avoid nausea, and cooks combinations that should not work but occasionally do. His friends have learned that being invited over is not always a good sign.`,
  `Karak once attempted to grow a tulsi plant, which was promptly eaten by monkeys. This escalated into a brief conflict involving a wooden bat, a retaliatory bite, and a rooftop escape that he maintains was strategically sound.He went on to study architecture and later design, eventually working on systems that help shopkeepers decide what to sell and why. He is particularly good at anticipating edge cases, including ones that have not yet occurred.He now lives in Bengaluru, where he continues to design, cook, and avoid long-term commitments to things that cannot defend themselves.`,
  `Karak works on building tools that help small shopkeepers understand profit, demand, and risk, often with incomplete information and unreliable networks. He believes prosperity should be distributed more evenly, though he has yet to design a system that agrees.His education moved from architecture in Haryana to design in Rajasthan, a transition that replaced physical structures with invisible ones. He adapted by becoming good at breaking down complex problems into smaller problems that are slightly less annoying.He spends his time in Bengaluru building systems, small form factor computers, and meals that appear questionable but are defended with confidence.`,
  `Karak briefly considered leaving design to pursue work that felt more meaningful, including a period that may or may not have involved seasonal farm work across different countries. Details remain inconsistent, but the conviction was real.He has since returned to product design, where the problems are clearer but the meaning requires more imagination. He continues to believe that work should be useful, even if it is not always fulfilling.He currently lives in Bengaluru, where he cooks, designs, and keeps his options open in case leaving again becomes necessary.`,
  `Karak once attempted to teach in Bastar, driven by the idea that structured thinking could be more useful outside corporate systems. The experience was sincere, educational, and shorter than expected.He returned to design, where ambiguity is constant and outcomes are rarely final. This has not improved his clarity, but it has made him more patient with confusion.He now lives in Bengaluru, where he balances work, food experiments, and the occasional urge to relocate his entire life without warning.`,
  `Karak’s long-term plan involves a house in the Western Ghats, partially built over water, with a door that allows for immediate exits during moments of frustration. This is considered both an architectural decision and an emotional safety feature.Until then, he works as a product designer in Bengaluru, building systems for millions of users while occasionally questioning the direction of all of them. He owns a knife sharpener he does not fully understand, a second-hand IKEA bed meant for children, and a watch that is slowly giving up.He continues to cook quickly, think slowly, and prepare for a life that will either make complete sense or none at all.`,
];

export const MINFO_BIO_VARIANTS = BIO_VARIANT_BODIES.map(
  (body) => `${BIO_HEADER}\n\n${body}`.trim(),
);
