const BIO_HEADER = `[**Bio**](https://portofliokarak.vercel.app/blog/minfo)

→
September 27, 2020 \\| Reading time: 8 minutes
`;

const BIO_VARIANT_BODIES = [
  `I was born in Howrah, grew up in Faridabad, and eventually found my way to Jhalda, where elephants occasionally show up to steal jackfruits and leave without explanation. This early exposure to unpredictable systems prepared me well for a career in product design. I studied architecture in Murthal before moving to Jodhpur for design, trading concrete for constraints and buildings for user flows. I now design systems for shopkeepers using 4G internet that behaves like 3G, on phones that are already out of memory and patience. I currently live in Bengaluru, where I cook quickly, avoid cleaning utensils, and distrust restaurants that look recently renovated. I suspect that if something works too smoothly, it probably hasn’t been tested properly.`,
  `I believe that good food is inversely proportional to how clean a place looks. This theory has led me to eat at establishments that appear structurally uncertain but socially validated. Raised between dust, red soil, and mustard oil, I developed a habit of trusting environments that reveal themselves slowly. This instinct now informs my work designing for small businesses, where decisions are made under pressure and rarely revisited. I live in Bengaluru, drive with the windows open to avoid nausea, and cook combinations that should not work but occasionally do. My friends have learned that being invited over is not always a good sign.`,
  `I once attempted to grow a tulsi plant, which was promptly eaten by monkeys. This escalated into a brief conflict involving a wooden bat, a retaliatory bite, and a rooftop escape that I maintain was strategically sound. I went on to study architecture and later design, eventually working on systems that help shopkeepers decide what to sell and why. I am particularly good at anticipating edge cases, including ones that have not yet occurred. I now live in Bengaluru, where I continue to design, cook, and avoid long-term commitments to things that cannot defend themselves.`,
  `I work on building tools that help small shopkeepers understand profit, demand, and risk, often with incomplete information and unreliable networks. I believe prosperity should be distributed more evenly, though I have yet to design a system that agrees. My education moved from architecture in Haryana to design in Rajasthan, a transition that replaced physical structures with invisible ones. I adapted by becoming good at breaking down complex problems into smaller problems that are slightly less annoying. I spend my time in Bengaluru building systems, small form factor computers, and meals that appear questionable but are defended with confidence.`,
  `I briefly considered leaving design to pursue work that felt more meaningful, including a period that may or may not have involved seasonal farm work across different countries. Details remain inconsistent, but the conviction was real. I have since returned to product design, where the problems are clearer but the meaning requires more imagination. I continue to believe that work should be useful, even if it is not always fulfilling. I currently live in Bengaluru, where I cook, design, and keep my options open in case leaving again becomes necessary.`,
  `I once attempted to teach in Bastar, driven by the idea that structured thinking could be more useful outside corporate systems. The experience was sincere, educational, and shorter than expected. I returned to design, where ambiguity is constant and outcomes are rarely final. This has not improved my clarity, but it has made me more patient with confusion. I now live in Bengaluru, where I balance work, food experiments, and the occasional urge to relocate my entire life without warning.`,
  `My long-term plan involves a house in the Western Ghats, partially built over water, with a door that allows for immediate exits during moments of frustration. This is considered both an architectural decision and an emotional safety feature. Until then, I work as a product designer in Bengaluru, building systems for millions of users while occasionally questioning the direction of all of them. I own a knife sharpener I do not fully understand, a second-hand IKEA bed meant for children, and a watch that is slowly giving up. I continue to cook quickly, think slowly, and prepare for a life that will either make complete sense or none at all.`,
];

export const MINFO_BIO_VARIANTS = BIO_VARIANT_BODIES.map(
  (body) => `${BIO_HEADER}\n\n${body}`.trim(),
);
